services:
  mint-ca:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mint-ca
    network_mode: host
    restart: unless-stopped

    environment:
      - MINT_MASTER_KEY=${MINT_MASTER_KEY}
      - MINT_DB_DRIVER=sqlite
      - MINT_DB_DSN=/data/mint-ca.db
      - MINT_LISTEN_ADDR=:8443
      - MINT_READ_TIMEOUT_SECONDS=30
      - MINT_WRITE_TIMEOUT_SECONDS=60
      - MINT_IDLE_TIMEOUT_SECONDS=120
      - MINT_CRL_REFRESH_INTERVAL_SECONDS=3600
      - MINT_TLS_DISABLED=false
      - MINT_LOG_LEVEL=debug
      - MINT_TLS_CERT=/data/server.crt
      - MINT_TLS_KEY=/data/server.key
      - MINT_ACME_ENABLED=true
      - MINT_ACME_BASE_URL=https://localhost:8443
      - MINT_ACME_EAB_REQUIRED=true
    ports:
      - "8443:8443"

    volumes:
      - mint-data:/data
volumes:
  mint-data:
